import React, { useState } from "react";


import useAxios from "../../hooks/useAxious";

const AISummaryModal = ({ lesson, comments }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState(null);
  const [error, setError] = useState(null);
  const axiosInstance = useAxios()

  const handleGenerateSummary = async () => {
    setIsOpen(true);
    if (summary) return; // already loaded, don't re-fetch
    setLoading(true);
    setError(null);

    try {
      const res = await axiosInstance.post(
      '/ai-summary',
        // `${import.meta.env.VITE_API_URL}/ai-summary`,
        {
          title: lesson.title,
          description: lesson.description,
          category: lesson.category,
          emotionalTone: lesson.emotionalTone,
          comments: comments || [],
        }
      );
      setSummary(res.data.summary);
    } catch (err) {
      setError("There was a problem generating the AI summary. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleClose = () => {
    setIsOpen(false);
  };

  const handleRetry = () => {
    setSummary(null);
    setError(null);
    handleGenerateSummary();
  };

  return (
    <>
      {/* Trigger Button */}
      <button
        onClick={handleGenerateSummary}
        id="ai-summary-btn"
        className="ai-summary-trigger-btn"
        title="Generate AI Summary"
      >
        <span className="ai-btn-icon">✨</span>
        <span className="ai-btn-text">AI Summary</span>
        <span className="ai-btn-badge">Powered by Gemini</span>
      </button>

      {/* Modal Overlay */}
      {isOpen && (
        <div className="ai-modal-overlay" onClick={handleClose}>
          <div
            className="ai-modal-container"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Modal Header */}
            <div className="ai-modal-header">
              <div className="ai-modal-title-group">
                <div className="ai-gemini-icon">✨</div>
                <div>
                  <h2 className="ai-modal-title">AI-Powered Summary</h2>
                  <p className="ai-modal-subtitle">Generated by Google Gemini</p>
                </div>
              </div>
              <button className="ai-close-btn" onClick={handleClose}>
                ✕
              </button>
            </div>

            {/* Lesson reference */}
            <div className="ai-lesson-ref">
              <span className="ai-lesson-ref-label">📖 Lesson:</span>
              <span className="ai-lesson-ref-title">{lesson.title}</span>
            </div>

            {/* Modal Body */}
            <div className="ai-modal-body">
              {/* Loading State */}
              {loading && (
                <div className="ai-loading-state">
                  <div className="ai-loading-orbs">
                    <div className="ai-orb ai-orb-1"></div>
                    <div className="ai-orb ai-orb-2"></div>
                    <div className="ai-orb ai-orb-3"></div>
                  </div>
                  <p className="ai-loading-text">
                    Gemini AI is analyzing this lesson...
                  </p>
                  <p className="ai-loading-subtext">
                    Extracting insights & key takeaways
                  </p>
                </div>
              )}

              {/* Error State */}
              {error && !loading && (
                <div className="ai-error-state">
                  <div className="ai-error-icon">⚠️</div>
                  <p className="ai-error-text">{error}</p>
                  <button className="ai-retry-btn" onClick={handleRetry}>
                    🔄 Try again
                  </button>
                </div>
              )}

              {/* Summary Content */}
              {summary && !loading && (
                <div className="ai-summary-content">
                  {/* Power Quote */}
                  {summary.powerQuote && (
                    <div className="ai-power-quote">
                      <span className="ai-quote-mark">"</span>
                      <p className="ai-quote-text">{summary.powerQuote}</p>
                      <span className="ai-quote-mark ai-quote-end">"</span>
                    </div>
                  )}

                  {/* Key Takeaways */}
                  <div className="ai-section">
                    <h3 className="ai-section-title">
                      <span className="ai-section-icon">🎯</span>
                      Key Takeaways
                    </h3>
                    <div className="ai-takeaways-list">
                      {summary.keyTakeaways?.map((item, idx) => (
                        <div key={idx} className="ai-takeaway-item">
                          <div className="ai-takeaway-num">{idx + 1}</div>
                          <p className="ai-takeaway-text">{item}</p>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Emotional Insight */}
                  <div className="ai-section">
                    <h3 className="ai-section-title">
                      <span className="ai-section-icon">💜</span>
                      Emotional Insight
                    </h3>
                    <div className="ai-insight-card">
                      <p className="ai-insight-text">{summary.emotionalInsight}</p>
                    </div>
                  </div>

                  {/* Suggested Action */}
                  <div className="ai-section">
                    <h3 className="ai-section-title">
                      <span className="ai-section-icon">⚡</span>
                      Today's Action Step
                    </h3>
                    <div className="ai-action-card">
                      <p className="ai-action-text">{summary.suggestedAction}</p>
                    </div>
                  </div>

                  {/* Community Mood */}
                  <div className="ai-section">
                    <h3 className="ai-section-title">
                      <span className="ai-section-icon">🌐</span>
                      Community Mood
                    </h3>
                    <div className="ai-community-card">
                      <p className="ai-community-text">{summary.communityMood}</p>
                    </div>
                  </div>

                  {/* Regenerate */}
                  <button className="ai-regenerate-btn" onClick={handleRetry}>
                    🔄 Regenerate Summary
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Scoped Styles */}
      <style>{`
        /* Trigger Button */
        .ai-summary-trigger-btn {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 10px 20px;
          background: linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%);
          color: white;
          border: none;
          border-radius: 50px;
          font-size: 14px;
          font-weight: 600;
          cursor: pointer;
          position: relative;
          overflow: hidden;
          transition: all 0.3s ease;
          box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4);
        }

        .ai-summary-trigger-btn::before {
          content: '';
          position: absolute;
          top: 0; left: -100%;
          width: 100%; height: 100%;
          background: linear-gradient(90deg, transparent, rgba(255,255,255,0.25), transparent);
          transition: left 0.5s ease;
        }

        .ai-summary-trigger-btn:hover::before {
          left: 100%;
        }

        .ai-summary-trigger-btn:hover {
          transform: translateY(-2px);
          box-shadow: 0 8px 25px rgba(102, 126, 234, 0.6);
        }

        .ai-btn-icon {
          font-size: 16px;
          animation: sparkle 2s ease-in-out infinite;
        }

        @keyframes sparkle {
          0%, 100% { transform: scale(1) rotate(0deg); }
          50% { transform: scale(1.2) rotate(10deg); }
        }

        .ai-btn-badge {
          font-size: 9px;
          background: rgba(255,255,255,0.25);
          padding: 2px 7px;
          border-radius: 20px;
          letter-spacing: 0.5px;
        }

        /* Modal Overlay */
        .ai-modal-overlay {
          position: fixed;
          inset: 0;
          background: rgba(0, 0, 0, 0.7);
          backdrop-filter: blur(8px);
          z-index: 9999;
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 16px;
          animation: fadeIn 0.2s ease;
        }

        @keyframes fadeIn {
          from { opacity: 0; }
          to { opacity: 1; }
        }

        /* Modal Container */
        .ai-modal-container {
          background: white;
          border-radius: 24px;
          width: 100%;
          max-width: 580px;
          max-height: 88vh;
          overflow: hidden;
          display: flex;
          flex-direction: column;
          box-shadow: 0 30px 80px rgba(0,0,0,0.3);
          animation: slideUp 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
        }

        @keyframes slideUp {
          from { opacity: 0; transform: translateY(40px) scale(0.95); }
          to { opacity: 1; transform: translateY(0) scale(1); }
        }

        /* Modal Header */
        .ai-modal-header {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          padding: 20px 24px;
          display: flex;
          align-items: center;
          justify-content: space-between;
          flex-shrink: 0;
        }

        .ai-modal-title-group {
          display: flex;
          align-items: center;
          gap: 12px;
        }

        .ai-gemini-icon {
          font-size: 28px;
          animation: sparkle 2s ease-in-out infinite;
        }

        .ai-modal-title {
          color: white;
          font-size: 18px;
          font-weight: 700;
          margin: 0;
        }

        .ai-modal-subtitle {
          color: rgba(255,255,255,0.7);
          font-size: 11px;
          margin: 2px 0 0 0;
        }

        .ai-close-btn {
          background: rgba(255,255,255,0.15);
          border: none;
          color: white;
          width: 32px;
          height: 32px;
          border-radius: 50%;
          cursor: pointer;
          font-size: 14px;
          transition: background 0.2s;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .ai-close-btn:hover {
          background: rgba(255,255,255,0.3);
        }

        /* Lesson Reference */
        .ai-lesson-ref {
          background: #f8f7ff;
          padding: 10px 24px;
          border-bottom: 1px solid #e8e5f5;
          display: flex;
          align-items: center;
          gap: 8px;
          flex-shrink: 0;
        }

        .ai-lesson-ref-label {
          font-size: 11px;
          color: #888;
          font-weight: 600;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          flex-shrink: 0;
        }

        .ai-lesson-ref-title {
          font-size: 13px;
          color: #555;
          font-weight: 500;
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
        }

        /* Modal Body */
        .ai-modal-body {
          padding: 24px;
          overflow-y: auto;
          flex: 1;
        }

        /* Loading State */
        .ai-loading-state {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          padding: 48px 24px;
          gap: 16px;
        }

        .ai-loading-orbs {
          display: flex;
          gap: 10px;
        }

        .ai-orb {
          width: 14px;
          height: 14px;
          border-radius: 50%;
          animation: bounce 1.2s ease-in-out infinite;
        }

        .ai-orb-1 { background: #667eea; animation-delay: 0s; }
        .ai-orb-2 { background: #764ba2; animation-delay: 0.2s; }
        .ai-orb-3 { background: #f093fb; animation-delay: 0.4s; }

        @keyframes bounce {
          0%, 60%, 100% { transform: translateY(0); }
          30% { transform: translateY(-16px); }
        }

        .ai-loading-text {
          font-size: 16px;
          font-weight: 600;
          color: #333;
          margin: 0;
        }

        .ai-loading-subtext {
          font-size: 13px;
          color: #888;
          margin: 0;
        }

        /* Error State */
        .ai-error-state {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 12px;
          padding: 40px;
          text-align: center;
        }

        .ai-error-icon { font-size: 40px; }
        .ai-error-text { color: #666; font-size: 14px; }

        .ai-retry-btn {
          background: linear-gradient(135deg, #667eea, #764ba2);
          color: white;
          border: none;
          padding: 10px 24px;
          border-radius: 50px;
          cursor: pointer;
          font-weight: 600;
          font-size: 14px;
          transition: opacity 0.2s;
        }

        .ai-retry-btn:hover { opacity: 0.85; }

        /* Summary Content */
        .ai-summary-content {
          display: flex;
          flex-direction: column;
          gap: 20px;
        }

        /* Power Quote */
        .ai-power-quote {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          border-radius: 16px;
          padding: 20px 24px;
          display: flex;
          align-items: flex-start;
          gap: 8px;
          position: relative;
        }

        .ai-quote-mark {
          font-size: 40px;
          color: rgba(255,255,255,0.4);
          line-height: 1;
          font-family: Georgia, serif;
          flex-shrink: 0;
          margin-top: -8px;
        }

        .ai-quote-end {
          align-self: flex-end;
          margin-bottom: -8px;
          margin-top: 0;
        }

        .ai-quote-text {
          color: white;
          font-size: 15px;
          font-style: italic;
          font-weight: 500;
          line-height: 1.6;
          margin: 0;
          flex: 1;
        }

        /* Section */
        .ai-section {
          display: flex;
          flex-direction: column;
          gap: 10px;
        }

        .ai-section-title {
          font-size: 14px;
          font-weight: 700;
          color: #444;
          display: flex;
          align-items: center;
          gap: 6px;
          margin: 0;
          text-transform: uppercase;
          letter-spacing: 0.8px;
        }

        .ai-section-icon { font-size: 16px; }

        /* Takeaways */
        .ai-takeaways-list {
          display: flex;
          flex-direction: column;
          gap: 10px;
        }

        .ai-takeaway-item {
          display: flex;
          align-items: flex-start;
          gap: 12px;
          background: #f8f7ff;
          border-radius: 12px;
          padding: 12px 16px;
          border-left: 3px solid #667eea;
        }

        .ai-takeaway-num {
          background: linear-gradient(135deg, #667eea, #764ba2);
          color: white;
          width: 24px;
          height: 24px;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 12px;
          font-weight: 700;
          flex-shrink: 0;
        }

        .ai-takeaway-text {
          color: #444;
          font-size: 14px;
          line-height: 1.5;
          margin: 0;
          padding-top: 2px;
        }

        /* Cards */
        .ai-insight-card {
          background: linear-gradient(135deg, #fce4f7, #e8d5fb);
          border-radius: 12px;
          padding: 14px 18px;
          border-left: 3px solid #c084fc;
        }

        .ai-insight-text {
          color: #5b3279;
          font-size: 14px;
          line-height: 1.6;
          margin: 0;
        }

        .ai-action-card {
          background: linear-gradient(135deg, #d1fae5, #a7f3d0);
          border-radius: 12px;
          padding: 14px 18px;
          border-left: 3px solid #34d399;
        }

        .ai-action-text {
          color: #065f46;
          font-size: 14px;
          line-height: 1.6;
          margin: 0;
          font-weight: 500;
        }

        .ai-community-card {
          background: linear-gradient(135deg, #fef3c7, #fde68a);
          border-radius: 12px;
          padding: 14px 18px;
          border-left: 3px solid #f59e0b;
        }

        .ai-community-text {
          color: #78350f;
          font-size: 14px;
          line-height: 1.6;
          margin: 0;
        }

        /* Regenerate Button */
        .ai-regenerate-btn {
          background: transparent;
          border: 2px solid #667eea;
          color: #667eea;
          padding: 10px 24px;
          border-radius: 50px;
          cursor: pointer;
          font-weight: 600;
          font-size: 13px;
          transition: all 0.2s ease;
          align-self: center;
          margin-top: 4px;
        }

        .ai-regenerate-btn:hover {
          background: #667eea;
          color: white;
        }
      `}</style>
    </>
  );
};

export default AISummaryModal;
